# Generated by Django 4.2.10 on 2024-02-29 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_name", models.CharField(max_length=255, unique=True, verbose_name="CompanyName")),
                (
                    "company_full_name",
                    models.CharField(blank=True, max_length=255, unique=True, verbose_name="CompanyFullName"),
                ),
                ("company_address", models.CharField(blank=True, max_length=255, verbose_name="CompanyAddress")),
                ("company_city", models.CharField(blank=True, max_length=255, verbose_name="CompanyCity")),
                ("company_country", models.CharField(blank=True, max_length=255, verbose_name="CompanyCountry")),
                ("company_email", models.EmailField(blank=True, max_length=254, verbose_name="CompanyEmail")),
                ("company_reg_number", models.CharField(blank=True, max_length=30, verbose_name="CompanyRegNumber")),
                ("company_vat_number", models.CharField(blank=True, max_length=30, verbose_name="CompanyVatNumber")),
                ("company_resident_company", models.BooleanField(default=False, verbose_name="CompanyResident")),
                (
                    "company_payment_currency",
                    models.CharField(
                        choices=[("EUR", "EUR"), ("DIN", "DIN")],
                        default="EUR",
                        max_length=3,
                        verbose_name="CompanyCurrency",
                    ),
                ),
                ("company_date_create", models.DateField(auto_now_add=True, verbose_name="CompanyDateCreate")),
            ],
        ),
        migrations.CreateModel(
            name="FuelCardIssuer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fci_name", models.CharField(max_length=255, unique=True, verbose_name="FCIName")),
                (
                    "fci_full_name",
                    models.CharField(blank=True, max_length=255, unique=True, verbose_name="FCIFullName"),
                ),
                ("fci_address", models.CharField(blank=True, max_length=255, verbose_name="FCIAddress")),
                ("fci_city", models.CharField(blank=True, max_length=255, verbose_name="FCICity")),
                ("fci_country", models.CharField(blank=True, max_length=255, verbose_name="FCICountry")),
                ("fci_email", models.EmailField(blank=True, max_length=254, verbose_name="FCIEmail")),
                ("fci_reg_number", models.CharField(blank=True, max_length=30, verbose_name="FCIRegNumber")),
                ("fci_vat_number", models.CharField(blank=True, max_length=30, verbose_name="FCIVatNumber")),
                ("fci_resident_company", models.BooleanField(default=False, verbose_name="FCIResident")),
                (
                    "fci_payment_currency",
                    models.CharField(
                        choices=[("EUR", "EUR"), ("DIN", "DIN")],
                        default="DIN",
                        max_length=3,
                        verbose_name="FCICurrency",
                    ),
                ),
                ("fci_date_create", models.DateField(auto_now_add=True, verbose_name="FCIDateCreate")),
            ],
        ),
        migrations.CreateModel(
            name="TAG",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tag_barcode_number",
                    models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name="TAGBarCode"),
                ),
                (
                    "tag_company_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="register.company",
                        verbose_name="CompanyName",
                    ),
                ),
                (
                    "tag_fci_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="register.fuelcardissuer",
                        verbose_name="FCIName",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type_of_service", models.CharField(max_length=255, unique=True, verbose_name="TypeOfService")),
                ("price_of_service", models.IntegerField(verbose_name="PriceOfService")),
                (
                    "service_fci_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="register.fuelcardissuer",
                        verbose_name="FCIName",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="company_fci_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="register.fuelcardissuer",
                verbose_name="FCIName",
            ),
        ),
    ]
